---
- name: test runas
  hosts: w2012r2
  vars_files:
    - vars/vars.yml

  tasks:
    - name: mkdir ansible
      win_file:
        path: "{{ work_dir }}"
        state: directory

    - name: copy ps1 script
      win_copy:
        src: src/ps1/DoRunAs.ps1
        dest: "{{ work_dir }}"

    - name: copy bat script
      win_copy:
        src: src/bat/Bat4Admin.bat
        dest: "{{ work_dir }}"

    - name: run batch runas
      win_shell: "{{ runas_ps1 }} {{ administrator_bat }}"
